version: "3.8"

services:
  db:
    container_name: mysql-apache
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 18766:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: wordpress-apache
    volumes:
    - ./:/var/www/html
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8181:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
